services:

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - inception-network
    ports:
      - "443:443"
    build:
      context: /home/bgrulois/inception/srcs/requirements/nginx
      dockerfile: Dockerfile
    env_file: .env 
    depends_on:
      - wordpress
    volumes:
      #- /home/bgrulois/data/wordpress 
      - wordpress:/var/www/wordpress
    restart: unless-stopped
  
  mariadb:
    image: mariadb
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - inception-network
    build:
      context: /home/bgrulois/inception/srcs/requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
      #  - /home/bgrulois/data/mariadb
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    expose:
      - "9000"
    networks:
      - inception-network
    build:
      context: /home/bgrulois/inception/srcs/requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      #- wordpress:/home/bgrulois/data/wordpress
      - wordpress:/var/www/wordpress
    restart: on-failure

volumes: 
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bgrulois/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bgrulois/data/mariadb'

networks:
  inception-network:
    driver: bridge
